services:
  - type: web
    name: intera-career-coach
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyADleIxGjqLePvyk6NFNMDQK480WpUiQt0
